version: '3.3'
volumes:
  nifi-database-repository:
  nifi-flowfile-repository:
  nifi-content-repository:
  nifi-provenance-repository:
  nifi-state:
  nifi-logs:
  nifi-nars:
  nifi-conf:
services:
  ldio-workflow:
    container_name: ${USECASE_NAME:-Verkeersboete}_ldio-workflow
    image: ghcr.io/informatievlaanderen/ldi-orchestrator:${LDIO_WORKFLOW_TAG:-20230224t1457}
    ports:
      - ${LDIO_WORKFLOW_PORT:-9003}:9003
    volumes:
      - ./ldio-workflow.config.yml:/application.yml:ro
    networks:
      - ldes
  ldes-server:
    container_name: ${USECASE_NAME:-Verkeersboete}_ldes-server
    image: ghcr.io/informatievlaanderen/ldes-server:${LDES_SERVER_TAG:-20230227t0812}
    environment:
      - SIS_DATA=/tmp
      - SPRING_DATA_MONGODB_DATABASE=${SPRING_DATA_MONGODB_DATABASE:-Verkeersboete}
      - LDES_COLLECTIONNAME=${LDES_COLLECTIONNAME:-verkeersboete}
      - LDES_MEMBERTYPE=${LDES_MEMBERTYPE:-https://politiezonex.be/ns/verkeersboete#Verkeersboete}
      - SPRING_DATA_MONGODB_HOST=ldes-mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - LDES_HOSTNAME=http://${HOSTNAME}:${LDES_SERVER_PORT:-8080}
      - LDES_SHAPE=${LDES_SHAPE:-}
      - VIEW_TIMESTAMPPATH=${VIEW_TIMESTAMPPATH:-http://www.w3.org/ns/prov#generatedAtTime}
      - VIEW_VERSIONOFPATH=${VIEW_VERSIONOFPATH:-http://purl.org/dc/terms/isVersionOf}
      # default view by time
      - VIEWS_0_NAME=${VIEWS_0_NAME:-by-page}
      - VIEWS_0_FRAGMENTATIONS_0_NAME=pagination
      - VIEWS_0_FRAGMENTATIONS_0_CONFIG_MEMBERLIMIT=${VIEWS_0_FRAGMENTATIONS_0_CONFIG_MEMBERLIMIT:-20}
    ports:
      - ${LDES_SERVER_PORT:-8080}:8080
    networks:
      - ldes
    depends_on:
      - ldes-mongodb
  ldes-mongodb:
    container_name: ${USECASE_NAME:-Verkeersboete}_ldes-mongodb
    image: mongo:${MONGODB_TAG:-6.0.4}
    ports:
      - ${MONGODB_PORT:-27017}:27017
    networks:
      - ldes
  nifi:
    image: ghcr.io/informatievlaanderen/ldi-workbench-nifi:20230417t154912
    container_name: ${USECASE_NAME:-Verkeersboete}_nifi
    restart: unless-stopped
    ports:
      # HTTPS
      - 8000:8000
      - 9004:9004
    volumes:
      - ./nifi-extensions:/opt/nifi/nifi-current/extensions
    environment:
      - NIFI_WEB_HTTP_PORT=${NIFI_UI_PORT:-8000}
      #- NIFI_JVM_HEAP_INIT=8g
      #- NIFI_JVM_HEAP_MAX=8g
    networks:
      - ldes
  graphdb:
    image: ontotext/graphdb:10.0.2
    container_name: ${USECASE_NAME:-Verkeersboete}_graphdb
    ports:
      # HTTP
      - 7200:7200
    networks:
      - ldes
networks:
  ldes:
    name: ${USECASE_NAME:-Verkeersboete}_network
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
